import { defineType, defineArrayMember } from "sanity";

export default defineType({
  name: "pageBuilder",
  title: "Page Builder",
  type: "array",
  of: [
    defineArrayMember({ type: "hero" }),
    defineArrayMember({ type: "textBlock" }),
    defineArrayMember({ type: "cta" }),
    defineArrayMember({ type: "featureGrid" }),
    defineArrayMember({ type: "statsCounter" }),
    defineArrayMember({ type: "logoBar" }),
    defineArrayMember({ type: "imageGallery" }),
    defineArrayMember({ type: "videoEmbed" }),
    defineArrayMember({ type: "testimonials" }),
    defineArrayMember({ type: "faq" }),
    defineArrayMember({ type: "teamGrid" }),
    defineArrayMember({ type: "contactForm" }),
    defineArrayMember({ type: "homepageHero" }),
    defineArrayMember({ type: "partnersTicker" }),
    defineArrayMember({ type: "whyPillars" }),
    defineArrayMember({ type: "locationMap" }),
    defineArrayMember({ type: "projectsGrid" }),
    defineArrayMember({ type: "incentivesGrid" }),
    defineArrayMember({ type: "ctaBanner" }),
    // New homepage modules
    defineArrayMember({ type: "statsBar" }),
    defineArrayMember({ type: "communitySection" }),
    defineArrayMember({ type: "valueProps" }),
    defineArrayMember({ type: "mapSection" }),
    defineArrayMember({ type: "industriesGrid" }),
    defineArrayMember({ type: "momentumSection" }),
  ],
});
