import { defineType, defineArrayMember } from "sanity";

export default defineType({
  name: "pageBuilder",
  title: "Page Builder",
  type: "array",
  of: [
    defineArrayMember({ type: "hero" }),
    defineArrayMember({ type: "textBlock" }),
    defineArrayMember({ type: "cta" }),
    defineArrayMember({ type: "featureGrid" }),
    defineArrayMember({ type: "statsCounter" }),
    defineArrayMember({ type: "logoBar" }),
    defineArrayMember({ type: "imageGallery" }),
    defineArrayMember({ type: "videoEmbed" }),
    defineArrayMember({ type: "testimonials" }),
    defineArrayMember({ type: "faq" }),
    defineArrayMember({ type: "teamGrid" }),
    defineArrayMember({ type: "contactForm" }),
    defineArrayMember({ type: "homepageHero" }),
    defineArrayMember({ type: "partnersTicker" }),
    defineArrayMember({ type: "whyPillars" }),
    defineArrayMember({ type: "locationMap" }),
    defineArrayMember({ type: "projectsGrid" }),
    defineArrayMember({ type: "incentivesGrid" }),
    defineArrayMember({ type: "ctaBanner" }),
    defineArrayMember({ type: "statsBar" }),
    defineArrayMember({ type: "communitySection" }),
    defineArrayMember({ type: "valueProps" }),
    defineArrayMember({ type: "mapSection" }),
    defineArrayMember({ type: "industriesGrid" }),
    defineArrayMember({ type: "momentumSection" }),
    defineArrayMember({ type: "contactInfo" }),
    defineArrayMember({ type: "detailedStats" }),
    defineArrayMember({ type: "projectShowcase" }),
    defineArrayMember({ type: "developmentAreaShowcase" }),
    defineArrayMember({ type: "incentiveCards" }),
    defineArrayMember({ type: "tifSection" }),
    defineArrayMember({ type: "resourceHub" }),
  ],
  options: {
    insertMenu: {
      filter: true,
      groups: [
        {
          name: "heroes",
          title: "Heroes & Headers",
          of: ["homepageHero", "hero"],
        },
        {
          name: "content",
          title: "Content",
          of: [
            "textBlock",
            "featureGrid",
            "imageGallery",
            "videoEmbed",
            "testimonials",
            "faq",
            "resourceHub",
          ],
        },
        {
          name: "stats",
          title: "Stats & Data",
          of: ["statsCounter", "statsBar", "detailedStats", "momentumSection"],
        },
        {
          name: "people",
          title: "People & Community",
          of: ["teamGrid", "communitySection", "partnersTicker", "logoBar"],
        },
        {
          name: "location",
          title: "Location & Projects",
          of: [
            "locationMap",
            "mapSection",
            "projectsGrid",
            "projectShowcase",
            "developmentAreaShowcase",
          ],
        },
        {
          name: "incentives",
          title: "Incentives & Business",
          of: [
            "incentivesGrid",
            "incentiveCards",
            "industriesGrid",
            "whyPillars",
            "valueProps",
            "tifSection",
          ],
        },
        {
          name: "cta",
          title: "Calls to Action",
          of: ["cta", "ctaBanner", "contactForm", "contactInfo"],
        },
      ],
    },
  },
});
